[package]
name = "foundry"
version = "0.1.0"
authors = ["currysoup <sam92cutler@hotmail.co.uk>"]

[dependencies]
docopt = "0.6.70"
docopt_macros = "0.6.70"
gl = "0.0.12"
rustc-serialize = "0.3.15"
sdl2 = "0.6.1"
sdl2_ttf = "0.6.0"

#cargo = "0.4.0"
